export {default as Dashboard} from './Dashboard'
export {default as Register} from './Register'
export {default as Error} from './Error'
export {default as Landing} from './Landing'
export {default as Login} from './Login'
export {default as Stats} from './Stats'
export {default as Profile} from './Profile'
export { default as AllJobs } from './AllJobs'
export { default as AddJobs } from './AddJobs'
export { default as EditJobs } from './EditJobs'